CREATE TABLE CustomerTable(
	cid			BIGINT			PRIMARY KEY	AUTO_INCREMENT,
	name		VARCHAR(10)		NOT NULL,
	ssn			VARCHAR(14)		NOT NULL,
	regDate		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP()
) AUTO_INCREMENT = 1001;

DROP TABLE CustomerTable;
CREATE TABLE AccountTable(
	aid				BIGINT		PRIMARY KEY AUTO_INCREMENT,
	accType			CHAR(1)		NOT NULL,
	balance			DOUBLE		NOT NULL	DEFAULT 0.0,
	interestRate	DOUBLE		NOT NULL	DEFAULT 0.0,
	overdraftAmount	DOUBLE		NOT NULL	DEFAULT 0.0,
	customerId		BIGINT		NOT NULL,
	regDate			TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT	AccountTable_customerId_FK	FOREIGN KEY (customerId)	REFERENCES CustomerTable(cid)
) AUTO_INCREMENT = 3001;
